### ISSUE TITLE
Provide script to upload files to Azure Blob Storage

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.scripting#10]
Provide script to upload files to Azure Blob Storage

**Comment by mbraekman** [comment]
Based on the following script:
https://codit.visualstudio.com/Invictus%20Templates/_git/invictus-templates?path=%2Fdeploy%2FInfra-UploadFilesToBlob.ps1

**Comment by stijnmoreels** [comment]
Probably in `Arcus.Scripting.Storage.Blob` PS module.
