### ISSUE TITLE
Azure File Share: Provide Script to create folders within a File Share

### ISSUE THREAD

**Issue by mbraekman** [arcus-azure/arcus.scripting#103]
**Is your feature request related to a problem? Please describe.**
Currently, this is not supported through ARM-templates, hence the idea to create a PS-script for this being part of the **Arcus.Scripting.Storage.FileShare**

**Describe the solution you'd like**
Something similar to this:
https://github.com/mbraekman/Powershell/blob/master/Azure/AzureStorage-CreateFolderWithinAzureFileShare.ps1

Suggested command name (open to better suggestions):
- _Create-AzFileShareStorageFolder_

**Describe alternatives you've considered**
Since ARM-templates do not support this, the alternative is to create it manually.

**Comment by stijnmoreels** [comment]
A bit strange to add it to a patch release? Maybe make it v0.3?

**Comment by mbraekman** [comment]
> A bit strange to add it to a patch release? Maybe make it v0.3?

You are absolutely right! My mistake; should've been the next full release.
