### ISSUE TITLE
Provide script AzDevOpsArmOutputsToPipelineVariables

### ISSUE THREAD

**Issue by mbraekman** [arcus-azure/arcus.scripting#113]
**Is your feature request related to a problem? Please describe.**
Limited version to the current ´Set-AzDevOpsArmOutputsToVariableGroup´, where the outputs of the ARM-template are only added as en environment-variable, instead of a variable group + environment variable.

**Describe the solution you'd like**
Could be added by adding an additional parameter to the existing ´Set-AzDevOpsArmOutputsToVariableGroup´, however naming-wise this is not correct, as we wouldn't be adding anything to a variable group.
Hence create a separate script: ´Set-AzDevOpsArmOutputsToEnvironmentVariables´
This would fix automatic creation of variable groups, while variables are only required as environment variable instead.

**Comment by stijnmoreels** [comment]
A new feature, should be moved to v0.3?

**Comment by stijnmoreels** [comment]
Also, I think we mean 'pipeline variables' here when we talk about 'environment variables'? Since the current `Set-AzDevOpsArmOutputsToVariableGroup` sets pipeline variables.

**Comment by mbraekman** [comment]
> A new feature, should be moved to v0.3?

Well, in fact currently we're using the existing script to achieve this, but this also triggers the creation of a variable group.
So not completely a new feature, more of a trimmed down version of what we already have. If that makes sense.

**Comment by mbraekman** [comment]
> Also, I think we mean 'pipeline variables' here when we talk about 'environment variables'? Since the current `Set-AzDevOpsArmOutputsToVariableGroup` sets pipeline variables.

You're right about this one -> pipeline variable instead of environment variable - my bad

**Comment by stijnmoreels** [comment]
> > A new feature, should be moved to v0.3?
> 
> Well, in fact currently we're using the existing script to achieve this, but this also triggers the creation of a variable group.
> So not completely a new feature, more of a trimmed down version of what we already have. If that makes sense.

Aha, yeah I see. I'll pick this up.
