### ISSUE TITLE
Provide script to automatically delete old deployments on an Azure Resource Group

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.scripting#12]
Provide script to automatically delete old deployments on an Azure Resource Group

**Comment by mbraekman** [comment]
Based on the following script:
https://codit.visualstudio.com/Invictus%20Templates/_git/invictus-templates?path=%2Fdeploy%2FAzure-RemoveOldArmDeployments.ps1

**Comment by tomkerkhove** [comment]
This will no longer be required 🎉 
https://docs.microsoft.com/en-us/azure/azure-resource-manager/templates/deployment-history-deletions?tabs=azure-powershell

**Comment by mbraekman** [comment]
Yes, saw that one pass by as well, woohoow! Finally!

**Comment by mbraekman** [comment]
Closing this, as it will no longer be required, see link above, posted by Tom.
