### ISSUE TITLE
Provide script to upload a certificate in the APIM Certificate store

### ISSUE THREAD

**Issue by mbraekman** [arcus-azure/arcus.scripting#136]
**Is your feature request related to a problem? Please describe.**
Provide script to upload a certificate in the APIM Certificate store.
This allows you to upload private certificates to be used for authenticating against backend services.

**Describe the solution you'd like**
In order to upload a private certificate, you need to perform these steps:
- Get APIM Context
- Create new AzApiManagementCertificate referring to the APIM-context.

_See: https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/new-azapimanagementcertificate?view=azps-5.5.0_

This would have the following parameters:
- ResourceGroupName (resource group containing the APIM instance)
- ServiceName (name of the APIM instance)
- CertificateFilePath (full path to the location of the public certificate)
- CertificatePassword (password for the private certificate)

Target-module:
- Arcus.Scripting.ApiManagement

**Describe alternatives you've considered**
Manual uploading of private certificates.

**Comment by stijnmoreels** [comment]
Voorlopig lijkt het password required, dus zullen we voorlopig niet kunnen gebruiken voor public certificates. Right?
https://github.com/Azure/azure-powershell/issues/12571
