### ISSUE TITLE
Provide script to import policy to an API in Azure API Management

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.scripting#14]
Provide script to import policy to an API in Azure API Management

**Comment by mbraekman** [comment]
For my understanding, what exactly would be the difference between this and #13 
Do you mean creating a separate script to import a base-policy vs an operation-specific policy?

**Comment by tomkerkhove** [comment]
The reasoning was to provide a script per "scope" so that we can provide parameters around what is needed to get the job done so that it's straightforward.

We could create one script to cover all scopes and decide based on provided parameters but, personally, I feel that's less user-friendly/readible; but happy to consolidate if I'm the only one

**Comment by mbraekman** [comment]
Might be more userfriendly indeed - let's make sure we split up all these kind of script then, incl. start/stop/...

**Comment by tomkerkhove** [comment]
Definately!

**Comment by mbraekman** [comment]
Based on the following script - more specifically the section where no `OperationId `has been specified:
https://codit.visualstudio.com/Invictus%20Templates/_git/invictus-templates?path=%2Fdeploy%2FApim-ImportApiPolicy.ps1
