### ISSUE TITLE
Functionality to add an access policy to Key Vault 

### ISSUE THREAD

**Issue by pim-simons** [arcus-azure/arcus.scripting#146]
**Is your feature request related to a problem? Please describe.**
Adding an access policy to Key Vault through an ARM template causes the access policies that are already there to be removed.

**Describe the solution you'd like**
A script that allows us to add an access policy to Key Vault that does not remove the current access policies on the Key Vault.

**Comment by mbraekman** [comment]
Thanks for the suggestion.

This can be based upon the following (but improved upon of course and moved out of the AzureRm-realm): https://github.com/mbraekman/Powershell/blob/master/Azure/Assign%20AccessPolicy%20to%20KeyVault.ps1

How do you see it when passing along the specific permissions?
- How would you see it being defaulted? Default None, requesting a string[] for the list of parameters?
- Using default "profiles" to set a range of permissions (as is the case in the Azure Portal)
- Do you want to provide the objectId of the user/group to which an access policy should be assigned? Or do we have to look it up based on some value?

**Comment by pim-simons** [comment]
**- How would you see it being defaulted? Default None, requesting a string[] for the list of parameters?**
I have been using the az keyvault set-policy command and we could probably use the same setup regarding the parameters: [https://docs.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest#az_keyvault_set_policy](https://docs.microsoft.com/en-us/cli/azure/keyvault?view=azure-cli-latest#az_keyvault_set_policy). Default to None would be good. 

**- Using default "profiles" to set a range of permissions (as is the case in the Azure Portal)**
Good solution I think. 

**- Do you want to provide the objectId of the user/group to which an access policy should be assigned? Or do we have to look it up based on some value?**
Maybe we could have 2 options, one to supply the objectid and one to supply a lookup value.

**Comment by mbraekman** [comment]
Note: regarding the profiles -> to be investigated if we can retrieve them from the azure portal somehow, otherwise it might become a PITA to maintain, but would be a useful addition to this script.

**Comment by pim-simons** [comment]
Looking back at this now, all of the functionality I needed is available in the Set-AzKeyVaultAccessPolicy cmdlet, see https://docs.microsoft.com/en-us/powershell/module/az.keyvault/set-azkeyvaultaccesspolicy?view=azps-7.1.0. Using this command at the moment whenever I need this functionality. 

I don't see much value to be added on top of that cmdlet, unless someone else thinks otherwise we can probably close this issue.

**Comment by stijnmoreels** [comment]
Ok, no problem. We can close this then for now and can always come back to it. np.
