### ISSUE TITLE
Migrate all scripts from AzureRM to Az modules

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.scripting#147]
**Is your feature request related to a problem? Please describe.**
Migrate all scripts from AzureRM to Az modules

https://github.com/azure-deprecation/dashboard/issues/120

**Comment by mbraekman** [comment]
Has been taken care of (#2).
If you notice any scripts that are still referring to AzureRm instead of Az, feel free to log a bug (it's not deprecated yet, but should be considered deprecated from our point of view).

Closing this for now.

**Comment by tomkerkhove** [comment]
I need more ☕, sorry 😁
