### ISSUE TITLE
Streamline and improve module logging across PS modules

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.scripting#155]
**Is your feature request related to a problem? Please describe.**
Right now, we use solely the `Write-Host` to write diagnostic information. This is great for current session view, but we should look into a better approach that makes sure the logging isn't lost afterwards + we should come up with a more streamlined approach when we log in our PS modules.

**Describe the solution you'd like**
[`PSFramework`](https://psframework.org/documentation/documents/psframework/logging/basics/writing-messages.html) might by an option.

**Describe alternatives you've considered**
We could also start first with using more `Write-*` variants so that the output is more clearer and structured. (using `Write-Verbose` for tracing instead of `Write-Host` for example).

**Comment by mbraekman** [comment]
Not sure if we should go for an additional framework for this, as it adds an additional dependency, while in 99% of the cases I expect using the `Write-Host`/`Write-Error`/...-combination will definitely suffice.
But you are correct that perhaps we should have a better look at when to use which `Write-*`-operation.

**Comment by stijnmoreels** [comment]
Scheme of logging:
- Warning-like: Write-Warning "<message>"
- Trace-like: Write-Verbose "<message>"
- Success-like: Write-Host "<message>" -ForegroundColor Green
- Information-like: Write-Host "<message>"

**Comment by fgheysels** [comment]
fyi,
Write-Host is awrapper around Write-Information
https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/write-host?view=powershell-7.3

I think the above logging-scheme is OK.
