### ISSUE TITLE
Provide script to upload partners into an Integration Account

### ISSUE THREAD

**Issue by mbraekman** [arcus-azure/arcus.scripting#162]
**Is your feature request related to a problem? Please describe.**
In order to be able to upload partners (1 partner per json-file) into an Integration Account, this either has to be done manually or some custom scripts.
Since there is already [a script](https://codit.visualstudio.com/invictus%20Templates/_git/invictus-templates?path=%2Fdeploy%2FIntegration-DeployIntegrationAccountArtifacts.ps1) that offers this functionality (in a bigger picture) we can extract the logic to upload partners into a separate script. 
This allows users to either only upload partners, or run the larger command to upload all available Integration Account artifacts.

The given script uses the REST API since no scripts were available yet at the time, or it had severe limitations.
To be checked whether this can be replaced by the following commands:
- [New-AzIntegrationAccountPartner](https://docs.microsoft.com/en-us/powershell/module/az.logicapp/new-azintegrationaccountpartner?view=azps-5.8.0)
- [Set-AzIntegrationAccountPartner](https://docs.microsoft.com/en-us/powershell/module/az.logicapp/set-azintegrationaccountpartner?view=azps-5.8.0)

**Describe the solution you'd like**
The script should accept the following parameters:
- IntegrationAccountName
  The name of the Integration Account to be targetted.
- IntegrationAccountResourceGroup
  The name of the resource group containing the Integration Account
- PartnersFolder
  Folder containing all JSON-files describing the partner objects to be created.
- ArtifactsPrefix (optional)
  When present, add this prefix to the name of the partners before uploading (in case of sharing an Integration Account across multiple environments in order to save costs.

**Additional context**
This is part of a number of scripts to upload artifacts into an Azure Integration Account, in order to replace the `Integration-DeployIntegrationAccountArtifacts.ps1` from the Invictus Templates.

**Comment by pim-simons** [comment]
@mbraekman do you have an example of a partner JSON file? Went through the code in the "old" script and I think it should be like this
```
{
  "name": "Partner1",
  "properties": {
    "partnerType": "B2B",
    "content": {
      "b2b": {
        "businessIdentities": [
          {
            "qualifier": "1",
            "value": "12345"
          },
          {
            "qualifier": "1",
            "value": "54321"
          }
        ]
      }
    }
  }
}
```

But just asking to be sure 😉

**Comment by pim-simons** [comment]
> @mbraekman do you have an example of a partner JSON file? Went through the code in the "old" script and I think it should be like this
> 
> ```
> {
>   "name": "Partner1",
>   "properties": {
>     "partnerType": "B2B",
>     "content": {
>       "b2b": {
>         "businessIdentities": [
>           {
>             "qualifier": "1",
>             "value": "12345"
>           },
>           {
>             "qualifier": "1",
>             "value": "54321"
>           }
>         ]
>       }
>     }
>   }
> }
> ```
> 
> But just asking to be sure 😉

I think I answered my own question, it is the JSON definition also available in the Azure Portal when you click here 
![image](https://user-images.githubusercontent.com/32359437/147763220-54e0fa3d-4789-497f-8ceb-f8c1b3cea8bf.png)

**Comment by mbraekman** [comment]
> 

Yep, that is the correct structure indeed 😄
