### ISSUE TITLE
Provide script to upload Integration Account Artifacts

### ISSUE THREAD

**Issue by mbraekman** [arcus-azure/arcus.scripting#165]
**Is your feature request related to a problem? Please describe.**
The currently existing [script ](https://codit.visualstudio.com/invictus%20Templates/_git/invictus-templates?path=%2Fdeploy%2FIntegration-DeployIntegrationAccountArtifacts.ps1)`Integration-DeployIntegrationAccountArtifacts.ps1` location in Invictus Templates, is to be migrated and optimized to allow creating/uploading artifacts into an Azure Integration Account.

This existing script is making use of the REST API due to (at the time of creation) limitations in the PowerShell function from AzureRm. Part of this task will be to investigate whether the new Az-module offers better support/performance than the current REST API implementation.

**Describe the solution you'd like**
The script should be accepting the following parameters:
- IntegrationAccountName
  The name of the Integration Account to be targetted.
- IntegrationAccountResourceGroup
  The name of the resource group containing the Integration Account
- ArtifactsFolder
  Folder containing all public certificates to be uploaded.
- ArtifactsPrefix (optional)
  When present, add this prefix to the name of the certificate before uploading (in case of sharing an Integration Account across multiple environments in order to save costs.

The following folder structure should be a prerequisite:
- \ArtifactsFolder\Schemas\Common 		Common schemas that need to be deployed first (dependencies)
- \ArtifactsFolder\Schemas				Default schema directory
- \ArtifactsFolder\Maps\Xslt				Xslt maps
- \ArtifactsFolder\Maps\Liquid			Liquid maps
- \ArtifactsFolder\Partners				EDI Partners
- \ArtifactsFolder\Agreements			EDI Agreements
- \ArtifactsFolder\Certificates				Public certificates

The scripts to be created in #159, #160, #161, #162, #163, #164 are to be used to upload all artifacts in the following order:
- schemas
- assemblies
- maps
- certificates
- partners
- assemblies

**Comment by pim-simons** [comment]
Schemas, assemblies, maps, certificates, partners and agreements have all been added to the scripts via https://github.com/arcus-azure/arcus.scripting/issues/159, https://github.com/arcus-azure/arcus.scripting/issues/160, https://github.com/arcus-azure/arcus.scripting/issues/161, https://github.com/arcus-azure/arcus.scripting/issues/162, https://github.com/arcus-azure/arcus.scripting/issues/163, https://github.com/arcus-azure/arcus.scripting/issues/164.
