### ISSUE TITLE
Get-AzKeyVaultAccessPolicies does not return a consistent result

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.scripting#166]
**Describe the bug**
When Get-AzKeyVaultAccessPolicies is run against a KeyVault that does not (yet) exists, the return-type is not the same as when it is run against a KeyVault that does exist.

**To Reproduce**
Run the Get-AzKeyVaultAccessPolicies script with parameters that reference a non existing KeyVault.

**Expected behavior**
The return value of this script must be an object with the same structure as when this script is run against a KV which does exist.

**Additional context**
This script is used in an Azure Devops pipeline.  We execute this script just before deploying an Azure KeyVault resource to retrieve the existing keyvault access policies of that KeyVault.  When (re)deploying the KeyVault resource we can then restore the existing access policies.
However, when you run the pipeline for the very first time, the KV obviously doesn't exist.  When you pass in the result of this script to the ARM template for deploying the KV, you then get an error.

**Comment by mbraekman** [comment]
I should have a look at how we handled this in the past, but would indeed make more sense to return an empty _list_ instead.
Thanks for the input.
