### ISSUE TITLE
Use real Azure resources in our integration tests

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.scripting#174]
**Is your feature request related to a problem? Please describe.**
In the very beginning, we only added scripts to the repo that were already tested in another repo. But this changes and so we are having some blind spots if it comes to the security and stability of our scripts.

**Describe the solution you'd like**
Use where we can real Azure resources (within the price limit) to test our current set of scripts.

**Comment by stijnmoreels** [comment]
Almost all things are (integration) tested. I see the following still open:
* Azure API Management (will not do bc it costs too much)
* Data Factory (don't really sure what's needed, or what it costs)
* Logic Apps (don't really sure what's needed)

Some things to be investigated.

**Comment by stijnmoreels** [comment]
So, we have already integration tests for Logic Apps, API Management is too expensive, and our Data Factory scripts are actually only a single one with a single function; so maybe also not the costs or effort worth?

**Comment by pim-simons** [comment]
> So, we have already integration tests for Logic Apps, API Management is too expensive, and our Data Factory scripts are actually only a single one with a single function; so maybe also not the costs or effort worth?

Only thing missing would indeed be Data Factory. From what I gather running costs would be low, but it would take some effort to build this as you would also need to create an actual flow within Data Factory. To me it seems like a bit too much effort for a single script and we can close this issue. @stijnmoreels  what do you think?

**Comment by stijnmoreels** [comment]
Yeah, @pim-simons , you're right. Looking at the code, the most important additions is exception handling, which is already tested in our unit tests. The script itself uses solely Azure PS commands, so seems indeed that this would be too big an effort.
We could come back to it if our Data Factory module is expanding or problems arise from people. 👍 

Closing this.
