### ISSUE TITLE
FileShare folder creation: HTTP 409 error when folder already existing

### ISSUE THREAD

**Issue by BramCoding** [arcus-azure/arcus.scripting#179]
**Describe the bug**
When using Arcus.Scripting.Storage.FileShare with command Create-AzFileShareStorageFolder creation of the folder is successful. When I retrigger my pipeline (and the folder already exists) I get following error:
![image](https://user-images.githubusercontent.com/38616745/122355876-8de82000-cf52-11eb-9458-b2334a2a7a45.png)

**To Reproduce**
-Execute an Azure Powershell step more than once in a release pipeline in DevOps using the Create-AzFileShareStorageFolder. When the folder already exists this error is thrown.

**Expected behavior**
I expected the command to check for the existance of the folder and if present: do nothing. If the folder is not present: create it.

**Additional context**
Azure Powershell version 5.185.0
Arcus version is latest I think. Imported using Install-Module -Name Arcus.Scripting.Storage.FileShare

**Comment by stijnmoreels** [comment]
Thanks @BramCoding for your issue! You are correct that this should not throw an failure when interacting with an already-created file share. Looking at the code, this should have prevented that, but we're working on more thorough integration tests with 'real' Azure resources to make sure we can circumvent these kind of problems in the future.

Is this something you want to take up?

**Comment by mbraekman** [comment]
As an add-on:
Just tried to run this locally (copy-paste from the actual script as a test) where the "already exists"-error has been handled appropriately. Will need some proper debugging to understand why it fails in the DevOps pipeline task.

![image](https://user-images.githubusercontent.com/16165565/122515181-5c805a80-d00d-11eb-926a-bea85a9e5ad9.png)

But highly agree with @stijnmoreels that extending the integration tests should heavily reduce this kind of situations.

**Comment by tomkerkhove** [comment]
Maybe the erorr is written as exit code and Azure DevOps picks that up?

**Comment by stijnmoreels** [comment]
@BramCoding, we made sure in that we used a different approach when handling existing Azure File Share folders. Instead of exceptions being throwed, expectedly, we choose to retrieve the existing folders and find one that matches.
This works on a Azure DevOps pipeline, so we hope it works for you too 😉 .

Will be available in the next version we release here.
Thanks again for remarking this!
