### ISSUE TITLE
Support for marking a build as 'retain indefinetely' in DevOps

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.scripting#182]
We have situations where our build / deploy pipeline produces artifacts that must be used / available by other pipelines.
By default, a pipeline-run is retained for 30 days, which is in our situation too short.  
Would it be an idea to provide a script via Arcus which allows you to retain the a build run indefinitely ?  This script can be called from within a pipeline and marks the current run as 'to be retained'.

(I can provide the script, as I've built it for a specific project).

**Comment by tomkerkhove** [comment]
Nice idea 👍

**Comment by mbraekman** [comment]
Always annoying when a build package is no longer available, so like the idea as well.

Are you achieving this by performing a _delete_-operation using the [Lease API](https://docs.microsoft.com/en-us/rest/api/azure/devops/build/leases?view=azure-devops-rest-6.0)?

Could you add what you have in a separate branch to extend the current DevOps-package?
We can always assist/jump in if it would be difficult (time-wise) for you.

**Comment by fgheysels** [comment]
Not via a delete operation :)  I have investigated the Lease API but decided to go with a PATCH operation on the Build API.

**Comment by mbraekman** [comment]
This is closed via the merge of PR #183
