### ISSUE TITLE
Provide a 'contribution-guide' for this project

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.scripting#188]
I'm currently contributing for the first time to this project, and as a non-Powershell expert, it would be nice to have some guidance available in the form of documentation.

This guide could describe what steps you need to take for certain topics:

- How to create a new module
- How to create a new script (create a ps1 file, make the required modifications in the psd1 and psm1 files, .... )
- How to create a unit test
- How to run the unit-tests  (I'm currently struggling on this step for instance, when running `Invoke-Pester -Path <file>`, I'm always faced with the error 'Module <modulename> is not a Script module>'.

**Comment by stijnmoreels** [comment]
+ How contributors with more privileges are able to release/prerelease the project
