### ISSUE TITLE
Migrate from AzureRm to Az

### ISSUE THREAD

**Issue by mbraekman** [arcus-azure/arcus.scripting#2]
Currently most of the PowerShell-scripts that are available are still referring to the AzureRM-module, which requires you to use v3.* of the Azure PowerShell pipeline task.

Since support for Az has been added in later versions and AzureRM is no longer being updated by MSFT, these scripts should be migrated in order to make use of Az-modules.

**Comment by tomkerkhove** [comment]
This is done I think?

**Comment by stijnmoreels** [comment]
> This is done I think?

It's a bit ongoing with the remaining issues that has still `AzureRm` 😅 . But this particular issue can maybe be closed in favor of the other/more specific ones.

**Comment by mbraekman** [comment]
Yes, it's being taken care of along the way - perhaps let's close this issue and ensure it's part of every other command being migrated/included.
