### ISSUE TITLE
Provide PowerShell syntax highlighting

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.scripting#208]
Provide PowerShell syntax highlighting for code samples.

Relates to https://github.com/arcus-azure/arcus/issues/113

**Comment by tomkerkhove** [comment]
@Mcalewaert is this something you can check please?

**Comment by Mcalewaert** [comment]
@tomkerkhove Created a PR for this

**Comment by tomkerkhove** [comment]
Thank you!
