### ISSUE TITLE
Only remove Azure API Management defaults if they exist

### ISSUE THREAD

**Issue by spasal** [arcus-azure/arcus.scripting#216]
**Is your feature request related to a problem? Please describe.**
Currently, one cannot use Arcus.Scripting.ApiManagement Remove-AzApiManagementDefaults in a CD pipeline without the task failing. After the first APIM deployment the default resources get successfully deleted, but afterwards the task fails because it tries to delete resource that do not exist anymore in APIM.

**Describe the solution you'd like**
Enhance the script to only try to delete the default resources if they exist.

**Describe alternatives you've considered**
If you set the errorActionPreference input to 'continue' on the AzurePowerShell@5 task, the task still succeeds but this is only a temporary workaround in my opinion.

**Additional context**
![image](https://user-images.githubusercontent.com/23562050/130046207-776e4cec-57a3-41e3-97f4-35a80bfae1a9.png)

**Comment by stijnmoreels** [comment]
Are finding everything you need @spasal , or do you need some help with something?

**Comment by tomkerkhove** [comment]
We should do a GET and only DELETE if it has a value
