### ISSUE TITLE
Provide script to set all entities in a specified Azure Table Storage

### ISSUE THREAD

**Issue by Annelotte-Mons** [arcus-azure/arcus.scripting#221]
**Is your feature request related to a problem? Please describe.**
Need for a way to version control the data (e.g. Configuration) set in a table storage.

**Describe the solution you'd like**
A script that first deletes all existing entities from a specified table, and then adds entities based on the contents of a configuration file (JSON).
In total, the configuration files will dictate what entities will be present on the Azure table storage.

**Comment by mbraekman** [comment]
Thanks for the good suggestion and PR ;)
