### ISSUE TITLE
Provide integration tests for the Invoke-SqlDatabaseMigration script

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.scripting#223]
We should provide a number of integration-tests for this script:

- [x] Check if the `DatabaseVersion` table is created when the script is ran on an empty database
      Arrange: Start with an empty database, DatabaseVersion table is not present
      Act: run the script (don't specify the schema parameter)
      Assert: Check if the DatabaseVersion table is created (optionally verify if the table-structure is as expected)
- [x] Check if the `DatabaseVersion` table is created in the correct (specified) schema
      Arrange: Start with an empty database, DatabaseVersion table is not present
      Act: run the script and specify the schema parameter
      Assert: Check if the DatabaseVersion table is created in the expected schema.
- [x] Check if the script correctly alters the DatabaseVersion table if that table still adhres to the old schema
      Assert: DatabaseVersion table exists but is still in the old table structure
      Assert: Verify if the DatabaseVersion table is correctly upgraded (majorversion, minorversion, patchversion)      
- [x] Check if migration scripts are correctly executed
     Arrange: create a database and pre-create the DatabaseVersion table; provide 2 'migration-files' which adhere to the following naming convention:  `{major}_{minor}_{patch}_{description}.sql`
     Act: run the script
     Assert: check if the database is in the expected version, by verifying if the `DatabaseVersion` table has the expected records present.  (Optionally check if the database has the expected changes (tables, added columns, ... )
- [x] Check if the `Invoke-SqlDatabaseMigration` still supports the 'old naming convention' of the migration filenames.
      Arrange: database with `DatabaseVersion` table is present.  Provide some migration-files that have a filename that follows this convent: `{Databaseversion}_{description}.sql` (f.i. `2_createsometable.sql`)
      Assert: Check if the `DatabaseVersion` contains the expected records.
- [x] Check if the `Invoke-SqlDatabaseMigration` supports the combination of 'old naming convention' migration files and migration files that follow the new naming convention.
      Arrange: database with `DatabaseVersion` table is present.  Provide some migration-files that have a filename that follows this convent: `{Databaseversion}_{description}.sql` (f.i. `2_createsometable.sql`) and have at least one migration file that follows this naming convention: `{maj}_{min}_{patch}_description.sql`
      Assert: Check if the `DatabaseVersion` contains the expected records.

- [x] Check if SQL errors in the migration scripts are handled as expected
     Arrange: create a database and pre-create the DatabaseVersion table; provide 2 'migration-files' which adhere to the following naming convention:  `{major}_{minor}_{patch}_{description}.sql`.  Make sure that there's an error in the 2nd migration file which cause the migration to fail. (f.i. remove a non existent column)
     Act: run the script
     Assert:  The DatabaseVersion table should have only one record which represents the version of the first migration file.

**Comment by stijnmoreels** [comment]
Related to #217

**Comment by fgheysels** [comment]
I think we can close this issue ?

**Comment by stijnmoreels** [comment]
> I think we can close this issue ?

Ah yes, we can always add more rests but this is already great, thx 👍
