### ISSUE TITLE
Proposal - project structure

### ISSUE THREAD

**Issue by mbraekman** [arcus-azure/arcus.scripting#23]
**Below is a suggestion for the structure of this repo.**
_Feedback is welcome_: @stijnmoreels, @tomkerkhove _(Tom: ignore this for the coming weeks!!)_ or anyone else reading this.

Since the purpose of this repo will not be limited to PowerShell, I suggest to start with the following structure:
   - /src/Arcus.Scripting.PowerShell/...
   - /docs/Arcus.Scripting.PowerShell/...

_Later on we can always add scripts for Bash,... depending on needs or suggestions_
 
As we are going to have several scripts related to multiple resource types/areas, I would like to suggest to create a PS-module per area:
  - Arcus.Scripting.PS.ApiManagement
  - Arcus.Scripting.PS.ARM
  - ...

This would prevent someone from having to pull all scripts while only those related to DataFactory, for instance, are required. We can also easily push new scripts or fixes related to a single area without impacting any others.

This means that for each of these area's, we will need a separate project (incl. psm1 & psd1), separate build/release and thus increasing the overhead.

Is this overhead acceptable for you? 
Do you agree with the proposed structure?
Any other suggestions?

Thanks for the feedback!

**Comment by stijnmoreels** [comment]
Yes, I can agree on the splitting by area/domain. That seems appropriate.

I would suggest for the docs, to not add this in the paths and more create a structue like the other Arcus projects:

* `./docs/features/arm.md
* `./docs/features/api-management.md`

And for preview and older versions:
* `./docs/preview/features/`
* `./docs/v0.1.0/features/`

Is this something you would agree to? Then we would have the same docs strucure here.

**Comment by mbraekman** [comment]
I like the idea of using a uniform structure across all projects, so your proposal for using the preview and version-folders, as is the case for the other projects, is fine by me!

I would like to make a separation based on the language as well. Even though it might seem overkill now and we might never need it, if we would ever expand do different languages we don't need any refactoring. 
Because I can see that someone who is interested in the PowerShell-documentation, wouldn't want to see any bash-related docs within the same page.

**Comment by stijnmoreels** [comment]
I'm currently working on a this proposal and the CI build so we have some 'starter' project and can begin with the actual implementation.

**Comment by tomkerkhove** [comment]
That's ok for me, but I would rename `ps` with `powershell` for sake of clarity.

**Comment by mbraekman** [comment]
Wanted to keep it short, but ok, might not be as clear -> agree with full name

**Comment by stijnmoreels** [comment]
Ok, this is already in place. Closing.
