### ISSUE TITLE
Provide script to upsert an app setting within an Azure App Service

### ISSUE THREAD

**Issue by mbraekman** [arcus-azure/arcus.scripting#236]
**Is your feature request related to a problem? Please describe.**
Updating a single application setting in an App Service cannot be done via ARM-/Bicep-templates.
This can be done via PowerShell, but requires a couple of actions to be performed.

**Describe the solution you'd like**
Create a new module:
  _Arcus.Scripting.AppService_
Create a new function: 
  _Set-AzAppServiceSetting_
  Parameters:
    - _ResourceGroupName_: resource group containing the app service
    - _AppServiceName_: the name of the app service of which the settings should be updated
    - _AppServiceSettingName_: the name of the app setting to be added/updated
    - _AppServiceSettingValue_: the value to be assigned to the app setting

**Describe alternatives you've considered**

**Additional context**
An initial implementation can be found here:
https://github.com/mbraekman/Powershell/blob/master/Azure/AppService-UpdateAppSetting.ps1

**Comment by stijnmoreels** [comment]
Great! Thx 😉
