### ISSUE TITLE
Inject-ArmContent: replacing newline characters doesn't work as expected anymore

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.scripting#242]
**Describe the bug**
For Build in Azure DevOps, I use the Inject-ArmContent of Arcus.Scripting.ARM to inject an xml policy inside a json arm template for an API.

`"policyContent": "${ FileToInject='policies\\inventorymgmt-dst-swire-base-policy.xml', EscapeJson, ReplaceSpecialChars }$"`

With a file like that:
```
<policies>
  <inbound>
    <base />
```
 
It works fine for months and amongst other things replaces the carriage returns by the characters \r\n :
 
`"policyContent": "<policies>\r\n  <inbound>\r\n    <base />\r\n   \r\n ` 
 
But now, without any change in my files, this does not work anymore and generates the following on multiple lines (and deployment fails…☹):
 
```
        "policyContent": "<policies>
\r\n  <inbound>
\r\n    <base />
\r\n   
```

**Comment by fgheysels** [comment]
I think we should create some additional tests for this ?

**Comment by stijnmoreels** [comment]
This is maybe related to this: https://github.com/arcus-azure/arcus.scripting/issues/197
That was also fixing something. I think this is maybe conflicting that one?

**Comment by fgheysels** [comment]
> This is maybe related to this: #197 That was also fixing something. I think this is maybe conflicting that one?

That was my idea as well :)

**Comment by stijnmoreels** [comment]
> I think we should create some additional tests for this ?

We have an open PR that makes sure our integration tests are always run on linux and windows. That's also a great imrprovement.

We also need some additional info for this bug: what version, what build image...

**Comment by fgheysels** [comment]
> > I think we should create some additional tests for this ?
> 
> We have an open PR #233 that makes sure our integration tests are always run on linux and windows. That's also a great imrprovement.

Thought I already reviewed & approved that one.   I've just approved it now, it should be completed within a few minutes (auto-merge :D ).

> 
> We also need some additional info for this bug: what version, what build image...

It occurred with the latest version (v0.5.0), as the person who reported this error didnt specify any version when installing the Arcus module.
Build image: idk.

Maybe @Muriel-B can add some additional information here ?

**Comment by Muriel-B** [comment]
OK

[Codit]<https://www.codit.eu/?utm_source=esignature&utm_medium=email&utm_campaign=coditwebsite>
Muriel Boutefeu​
Senior Consultant
m: +32471 99 03 36<tel:+32471%2099%2003%2036>
***@***.******@***.***>
 |
www<https://www.codit.eu/>.c<https://www.codit.eu/>odit.eu<https://www.codit.eu/>
[Making the move to Application Modernization]<https://www.codit.eu/blog/making-the-move-to-application-modernization/?utm_source=esignature&utm_medium=email&utm_campaign=whitepaper-making-the-move-to-application-modernization>

**Comment by Muriel-B** [comment]
I ran it on Windows. 

        pool:
          vmImage: "windows-latest"

I hadn't specify any version, so yes latest one  (v0.5.0).
