### ISSUE TITLE
SQL integration tests `BeforeAll`/`AfterAll` fails sometimes

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.scripting#245]
**Describe the bug**
When triggering the CI build, the SQL integration tests sometimes fail entirely. The tests aren't run but fail in the setup phase (`BeforeAll`/`AfterAll`).

**To Reproduce**
Run the CI build.

**Expected behavior**
All tests green.

**Additional context**
We should also look at the parallel/serial run for this. Maybe that's the problem.
 - Current version (v0.5)

**Comment by fgheysels** [comment]
I thought this has been fixed a few weeks / months ago ?

When creating the tests for the DB updates that supported semantic versioning, I also ran into this, but then it was due to the fact that the SQL Database where we run our tests against, was not running yet.  Fixed this by providing a warm up script if I'm not mistaken.
Is it the same problem, or is it related ?

**Comment by stijnmoreels** [comment]
Here's an example on `master` of current CI build: https://dev.azure.com/codit/Arcus/_build/results?buildId=57631&view=logs&j=08f80cb3-e007-5e07-fe7e-d964079b3df4&t=90d575db-4dd8-5dcb-2cbf-46d32c994f12&l=294

Seems like something wrong with the reading of a script file:
```
[-] Describe Arcus Azure SQL integration tests failed
 BatchParserException: Incorrect syntax was encountered while parsing ''.
 at <ScriptBlock>, /home/vsts/work/1/s/src/Arcus.Scripting.Tests.Integration/Arcus.Scripting.Sql.tests.ps1:102
```

Werid, bc when you run it again, it could work again. Seems like maybe indeed the database warming up. Maybe. 😅

**Comment by stijnmoreels** [comment]
Oh, the thing I also found: when a test run is cancelled, the setup / teardown don't always guarantee a clean environment when that test run is restarted. Needless to say, with using a single static Azure resource, we can't support parallel test runs, so we could also consider removing every table before running the SQL tests.

**Comment by fgheysels** [comment]
> Oh, the thing I also found: when a test run is cancelled, the setup / teardown don't always guarantee a clean environment when that test run is restarted. Needless to say, with using a single static Azure resource, we can't support parallel test runs, so we could also consider removing every table before running the SQL tests.

I think this is a good idea.   By doing this , we make sure that we start from a clean slate.
