### ISSUE TITLE
Unnecessary logging in Get-AzKeyVaultAccessPolicies.ps1

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.scripting#262]
I was looking at some logs of a devops pipeline  where I use the Get-AzKeyVaultAccessPolicies script to retrieve existing access policies, and I noticed a log-entry which doesn't bring any value to the table.

More specifically, I saw this:
> Current access policies: @{list=System.Object[]}

Which doesn't really give any added value imho.  This is just outputting the type of  the variable that contains the access policies, but not the access policies themselves.  Additionally, I wonder if we should even output the existing access policies here, as it can be quite a long list which contains a lot of information.  (For every access policy, the name of the object that has access + their rights).

I think we should just remove [this line of code](https://github.com/arcus-azure/arcus.scripting/blob/33eb4d6d6943efe349b1da574b7a1eeb10ce4c19/src/Arcus.Scripting.KeyVault/Scripts/Get-AzKeyVaultAccessPolicies.ps1#L47) from the Powershell script.

**Comment by stijnmoreels** [comment]
Yeah, I saw that too some time ago. We could definitely remove it, as it indeed doesn't add much value. We could, though, still log that we successfully retrieved the access policies. Or something like that. 👍

**Comment by pim-simons** [comment]
Assigned to me, but https://github.com/pimentacodit888 will be working on this 👍🏻
