### ISSUE TITLE
Uploading partners into Azure Integration Account integration tests not always stable

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.scripting#264]
**Describe the bug**
When uploading the partners into an Azure Integration Account during our integration tests, we sometimes get assertion failures on the `CreatedTime <> UTC now or UTC now (-1 s)` assertion.

A possible solution here would be to loosen the assertion. Only assert on the hour and date instead of be as precise as seconds.

**To Reproduce**
- Run Azure Integration Account integration tests.

**Expected behavior**
All green.

**Additional context**
https://github.com/arcus-azure/arcus.scripting/blob/33eb4d6d6943efe349b1da574b7a1eeb10ce4c19/src/Arcus.Scripting.Tests.Integration/Arcus.Scripting.IntegrationAccount.tests.ps1#L776
https://github.com/arcus-azure/arcus.scripting/blob/33eb4d6d6943efe349b1da574b7a1eeb10ce4c19/src/Arcus.Scripting.Tests.Integration/Arcus.Scripting.IntegrationAccount.tests.ps1#L849

**Comment by pim-simons** [comment]
Yeah this is probably my fault 🙄 
I was developing the script to upload agreements (see https://github.com/arcus-azure/arcus.scripting/pull/265) and was running the integration tests locally which probably interfered with your automated tests... I was wondering where my Partners in the integration account went, but this makes sense now.

Anything I can do to prevent this in the future, or is just this a coincidence we were running the tests at the same time (one locally and one automated)?

**Comment by stijnmoreels** [comment]
Yeah, I got the same again with uploading certificates.

> Anything I can do to prevent this in the future, or is just this a coincidence we were running the tests at the same time (one locally and one automated)?

I'm not entirely sure what Azure resources it uses, but I guess it's about a single static resource (much like we use a single SQL database for our tests). If there was a way that we could create/delete an integration account on each test run, that could maybe fix this.

**Comment by pim-simons** [comment]
Pipelines are all working again now, it seems to have been a matter of running automated tests through DevOps and by change running them locally at the same time as well. For now we will close the issue, but if this occurs more frequently in the future we can look at making all objects in the test cases unique.
