### ISSUE TITLE
Provide script to import API in Azure API Management based on WSDL

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.scripting#3]
Provide script to import API in Azure API Management based on WSDL

**Comment by tomkerkhove** [comment]
Cut

**Comment by mbraekman** [comment]
SOAP API's, and therefore WSDL's, might not be used that often anymore, but it is still used, so I don't immediately see why this shouldn't be part of this module.

**Comment by tomkerkhove** [comment]
I had a look at the script and it was a one-liner so that's why I removed it since it's not that much effort but open to anything!

**Comment by mbraekman** [comment]
I'll have to recheck the official documentation on this, as it was lacking decent information on use for wsdl's. This script was more _executable documentation_, but no point in creating functions for oneliners indeed.
