### ISSUE TITLE
Provide a release pipeline for Powershell gallery

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.scripting#30]
Provide a release pipeline for NuGet.org.
      
### Checklist
      
- [x] Build the codebase
- [x] Run test suite
- [x] Tag the codebase on success
- [x] Create a GitHub pre-release for a preview releases
- [x] Create a GitHub release for full releases
- [x] Push all Powershell cmdlet to Powershell gallery

**Comment by stijnmoreels** [comment]
Leave open for service connection that has to be made to PowerShell Gallery.

**Comment by tomkerkhove** [comment]
Already done ;)
