### ISSUE TITLE
Configure Netlify for creating preview documentation

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.scripting#31]
Configure Netlify for creating previews of documentation changes.
     
This allows us to more easily review documentation changes as a reviewer and also lowers the barrier to make documentation changes.
      
### Checklist
      
- [x] Create new Netlify site
- [x] Add Netlify configuration
- [x] Enforce checks on branches

**Comment by tomkerkhove** [comment]
Already available on https://arcus-scripting-staging.netlify.app/.

No checks need to be enforced as it only should be built for doc changes.

**Comment by tomkerkhove** [comment]
Example:
![image](https://user-images.githubusercontent.com/4345663/84014939-65126f80-a97b-11ea-9a1a-46436e8265db.png)
