### ISSUE TITLE
Add user guide to adding ARM outputs to DevOps variable groups

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.scripting#314]
**Is your feature request related to a problem? Please describe.**
To help our consumers, we should invest in user guides to highlight major features.

**Describe the solution you'd like**
Adding a user guide for our script that places ARM outputs to DevOps variable groups seems like a good way to help consumers.

**Additional context**
https://scripting.arcus-azure.net/features/powershell/azure-devops/#setting-arm-outputs-to-azure-devops-variable-group

**Comment by stijnmoreels** [comment]
Is this something you want to give a go, @pim-simons ? Or about another topic that you're familiar with? Seems like a good idea to add some real-life user-guides to this repo as it's a collection of many different things, maybe often used together.

**Comment by pim-simons** [comment]
Yeah this is something I can pick up, but I am a bit swamped in all kinds of other work as I just returned from vacation...
Do you have an example somewhere of such a user guide or will this be the first one? 
We could also collaborate on this, maybe you could create a blueprint with which kind of stuff you would like to have in the user guide and I can fill in the details? Just thinking out loud.

**Comment by stijnmoreels** [comment]
Yes sure, no problem. We have already some user guides in other repo's, a good example is in the Arcus security repo where we show how Azure Key Vault integration can be added:
https://github.com/arcus-azure/arcus.security/blob/master/docs/preview/02-Guides/add-secret-store-with-keyvault-integration.md

Also fine to do this together, but will indeed needs some help on the details as I've never done this 😅 .

**Comment by stijnmoreels** [comment]
Also: great to have you back from holiday! 😉

**Comment by stijnmoreels** [comment]
Maybe we can also look for some modules or commands that are used together, and start, for example, from a simple DevOps pipeline and add the Arcus stuff to it.

**Comment by fgheysels** [comment]
I'm a bit late to the party, but imho, adding outputs to variable groups is an anti-pattern  :) 
By doing that, you have no control over those variable groups, and I've learned that this tend to end in a big ball of mud where you no longer have an overview of what variables are still needed / used, etc...

**Comment by stijnmoreels** [comment]
> I'm a bit late to the party, but imho, adding outputs to variable groups is an anti-pattern :) By doing that, you have no control over those variable groups, and I've learned that this tend to end in a big ball of mud where you no longer have an overview of what variables are still needed / used, etc...

But we still provide this script and there's no planning yet to remove it, so maybe this anti-pattern is not yet being seen as an anti-pattern by the practices? If it is used in some contexts, then such a user-guide can still be helpful, I think.
