### ISSUE TITLE
Improve consistency in Powershell parameter-names

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.scripting#322]
I have seen that most parameters in the `Import-AzApiManagementApiPolicy` script are PascalCased, however, one parameter is camelCased.
It would be better to make sure that the same convention is used :)

https://github.com/arcus-azure/arcus.scripting/blob/master/src/Arcus.Scripting.ApiManagement/Scripts/Import-AzApiManagementApiPolicy.ps1

**Comment by stijnmoreels** [comment]
Woops. Thx for noting! 👍
