### ISSUE TITLE
Import-AzApiManagementApiPolicy script reports failure while it succeeds

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.scripting#323]
**Describe the bug**
I'm using the `Import-AzApiManagementApiPolicy` script in one of my pipelines, and the task that calls this script fails, because `Import-AzApiManagementApiPolicy` throws the error:

> Failed to update API policy, please check parameters

However, when I go to the API Management instance where I imported the policy, I can see that the policy is correctly imported.

I've inspected the code, and the return value of the `Set-AzApiManagementPolicy` cmdlet is checked.  However, when I execute that cmdlet myself, and inspect what that command returns, the return value seems to be $null.
Therefore, the `if` statement evaluates to false, and the script fails.

**Comment by stijnmoreels** [comment]
Woops, that is indeed not good. Maybe there is not a return value for that command, and we're checking unnecessary values.

**Comment by fgheysels** [comment]
I believe there is indeed no return value.   The [documentation](https://docs.microsoft.com/en-us/powershell/module/az.apimanagement/set-azapimanagementpolicy?view=azps-8.2.0#outputs) mentions that this cmdlet outputs a boolean.  
However, I captured the return value and outputted it, but nothing was written to the console:

![image](https://user-images.githubusercontent.com/3605786/186868705-e53f0140-0bdc-4371-9085-3f83135f6548.png)


![image](https://user-images.githubusercontent.com/3605786/186868588-d3eb2d7c-b9a3-45a0-ba8d-34a678732ac9.png)

**Comment by stijnmoreels** [comment]
Aha! That's no useful docs, then, of Microsoft.
Should we then do an additional remote call to verify that this policy is set instead of checking on the bool?

**Comment by pim-simons** [comment]
I was just looking at this, looking at the code we have to add `-Passthru` to get the boolean as a result: https://github.com/Azure/azure-powershell/blob/main/src/ApiManagement/ApiManagement.ServiceManagement/Commands/SetAzureApiManagementPolicy.cs#L171

**Comment by pim-simons** [comment]
Just did a test with `-PassThru` and this indeed works

**Comment by stijnmoreels** [comment]
Aha! Pim saves the day. Thx!
We didn't picked this up due to our budget for API Management, but it's good that we can improve it with issues coming in.
