### ISSUE TITLE
Relevance of `Arcus.Scripting.All` PowerShell module

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.scripting#347]
**Is your feature request related to a problem? Please describe.**
Currently, we have two `.All` PowerShell modules in our solution: 1 that collects all the Azure Storage-related modules, and 1 that collects all our modules. The problem with the second one is that it is harder to maintain and by time less relevant as there may be no scenarios that requires all our PowerShell modules.

**Describe the solution you'd like**
We can remove the `Arcus.Scripting.All` PowerShell module from our solution and provide a deprecation message in the PowerShell gallery saying that it will no longer be maintained and that references to more concrete modules is necessary.

**Comment by stijnmoreels** [comment]
Currently, this module is also not up-to-date as it does not contain all our PowerShell modules (like `Arcus.Scripting.IntegrationAccount` and `Arcus.Scripting.AppService`).

**Comment by fgheysels** [comment]
I'm in favor of removing the '.All' modules.  It is indeed true that there is no real use-case where you would want to pull in all modules.
