### ISSUE TITLE
Devops pipeline powershell failing after Import Arcus.Scripting.LogicApps

### ISSUE THREAD

**Issue by bramvanhautte** [arcus-azure/arcus.scripting#389]
**Describe the bug**
Since 23/05/2023 I am facing issues after importing the Arcus.Scripting.LogicApps powershell module. From the moment I import the module, no Powershell task is still working.

I am using a Hosted agent running on windows-latest and using the powershell@5 task in my YAML file.

**To Reproduce**
Take a DevOps Hosted agent running on windows-latest, use a powershell task to Import Arcus.Scripting.LogicApps and after that try to run a Powershell@5 task.

**Expected behavior**
Being able to run powershell scripts after Arcus.Scripting.LogicApps import

**Additional context**
Let me show you what happens and what I have spotted being an issue. I know that I have AzureRM and Az warnings but I am currently only using Az in this pipeline.

1) First off, I run a Powershell@5 task which outputs the value '1' for testing purposes. This works fine. Note that the Import-Module for Az.Accounts is automatically called and using folder path 2.12.2:

`- task: AzurePowerShell@5
  displayName: 'Powershell task before arcus import'
  inputs:
    azureSubscription: ${{ parameters.AzureSubscription }}
    ScriptType: 'InlineScript'
    Inline: 'Write-Output 1'
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true
  enabled: true`

![image](https://github.com/arcus-azure/arcus.scripting/assets/38616745/f9a98fd9-e406-4bd5-8206-95f02dab0ee9)

2) Then, I import the Arcus.Scripting.LogicApps module, which is successful:

`- pwsh: Install-Module -Name Arcus.Scripting.LogicApps -Scope CurrentUser -Force
  displayName: 'Installing Arcus.Scripting.LogicApps Powershell module'
  enabled: true`
  
![image](https://github.com/arcus-azure/arcus.scripting/assets/38616745/b9fa97ca-1e18-484e-82dd-e9abcda32bad)

3) After this, I try to run a Powershell@5 again but without success. Note how it now tries to import the Az.Accounts module from another path: 2.12.3:

`- task: AzurePowerShell@5
  displayName: 'Powershell task after arcus import'
  inputs:
    azureSubscription: ${{ parameters.AzureSubscription }}
    ScriptType: 'InlineScript'
    Inline: 'Write-Output 1'
    azurePowerShellVersion: 'LatestVersion'
    pwsh: true
  enabled: true`

![image](https://github.com/arcus-azure/arcus.scripting/assets/38616745/fb8e10b3-42da-4862-a8e2-b34d8c1538a0)

After the Arcus.Scripting.LogicApps import the Powershell@5 task tries to load a different Az.Account version which then conflicts with the current version it looks like.

**Comment by pim-simons** [comment]
I can indeed replicate the issue when using `Install-Module -Name Arcus.Scripting.LogicApps -Scope CurrentUser -Force`.

The suggestion from @fgheysels solves the error, if you use this to install the module then the pipeline should work correctly:
```
Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
Install-Module -Name Arcus.Scripting.LogicApps -AllowClobber
```

**Comment by fgheysels** [comment]
Can you re-produce the issue when you install the previous version of Arcus.Scripting instead ?

**Comment by pim-simons** [comment]
I searched through the entire codebase, the only reference I can find to `Az.Accounts` is in one of the test files [here](https://github.com/arcus-azure/arcus.scripting/blob/main/src/Arcus.Scripting.Tests.Unit/Arcus.Scripting.Management.tests.ps1#L3).

**Comment by fgheysels** [comment]
Can we reproduce this on other devops agents (linux for instance, or what if we do not use windows-latest but specify an actual version-nr instead )?

**Comment by bramvanhautte** [comment]
I will do some testing on the above. Update following soon.

**Comment by stijnmoreels** [comment]
@bramvanhautte , any update on this?
