### ISSUE TITLE
`Get-AzLogicAppRunHistory` command does not use the `-FollowNextPageLink` parameter

### ISSUE THREAD

**Issue by pim-simons** [arcus-azure/arcus.scripting#390]
**Describe the bug**
The scripts `Cancel-AzLogicAppRuns`, `Disable-AzLogicAppsFromConfig` and `Resubmit-FailedAzLogicAppRuns` use the `Get-AzLogicAppRunHistory` command but do not specify the `-FollowNextPageLink` parameter, meaning that only a subset of possible instances is returned. 

**To Reproduce**
Let 100 instances of a Logic App fail, run the `Resubmit-FailedAzLogicAppRuns` script and notice that not all failed Logic Apps have been resubmitted.

**Expected behavior**
Use the `-FollowNextPageLink` parameter on the `Get-AzLogicAppRunHistory` command.

**Comment by stijnmoreels** [comment]
Aha, that's an interesting case. Good that we will have this fixed. 👍
