### ISSUE TITLE
Provide script to grant a specific role to a resource on a specific resource group

### ISSUE THREAD

**Issue by mbraekman** [arcus-azure/arcus.scripting#40]
**Is your feature request related to a problem? Please describe.**
In some cases a resource needs to be granted access to all resources present within a specific resource group. To help in setting this up, a PS-script can be provided.

**Describe the solution you'd like**
This script should allow you to define:
- the name of the resource (and its RG) which should be granted access
- the name of the resource group to which access should be granted
- the name of the role to assign

for instance:
```
New-ResourceGroupRoleAssignment
 -TargetResourceGroupName
 -ResourceName
 -ResourceGroupName
 -RoleDefinitionName
```

**Additional context**
This script can be created based on the following:
https://codit.visualstudio.com/Invictus%20Templates/_git/invictus-templates?path=%2Fdeploy%2FInvictus-FlowHandlerAccessRights.ps1

**Comment by stijnmoreels** [comment]
Should probably be added to `Arcus.Scripting.Security`.
