### ISSUE TITLE
Add TrustServerCertificate param to Arcus.Scripting.Sql

### ISSUE THREAD

**Issue by LodewijkSioen** [arcus-azure/arcus.scripting#433]
**Is your feature request related to a problem? Please describe.**
I would like to use Arcus.Scripting.Sql to build up a local database for integration testing. However: recently the default for `TrustServerCertificate` has flipped from true to false. Arcus.Scripting.Sql does not provide a parameter to control this.

**Describe the solution you'd like**
An extra parameter that exposes `TrustServerCertificate`

**Describe alternatives you've considered**
Setting up certificates 😒

**Comment by stijnmoreels** [comment]
Great that you use Arcus.Scripting for this. Are you up to implement this yourself? We can guide you through the process.

**Comment by LodewijkSioen** [comment]
I'm cloning the repo and installing the powershell tooling as we speak ;)
I've already found the [Contributing](https://github.com/arcus-azure/arcus.scripting/blob/b7446c6da586106d1aece23acca72c7c363c7ce8/CONTRIBUTING.md) docs, but if there are other guidelines for a PR, let me know.

**Comment by stijnmoreels** [comment]
> I'm cloning the repo and installing the powershell tooling as we speak ;) I've already found the [Contributing](https://github.com/arcus-azure/arcus.scripting/blob/b7446c6da586106d1aece23acca72c7c363c7ce8/CONTRIBUTING.md) docs, but if there are other guidelines for a PR, let me know.

That's the most important one, the thing for PR's is that we place everything together (code changes + tests + docs) and not in separate PR's. But that's it.

Ping me or @pim-simons if you experience any trouble and thx a lot! 🤩

**Comment by LodewijkSioen** [comment]
Merged in #434
