### ISSUE TITLE
Documentation on how to install Arcus.Scripting is not correct

### ISSUE THREAD

**Issue by fgheysels** [arcus-azure/arcus.scripting#442]
The documentation that describes how to install an Arcus.Scripting module is not correct.

When you look at the [list of existing releases](https://github.com/arcus-azure/arcus.scripting/releases/tag/v1.4.0), we list the Powershell command that can be used to install an Arcus.Scrpting module, like this:

```
Install-Module -Name ... --Version 1.4.0
```

However, `--Version` is not an existing argument for the `Install-Module` command.  This must be `-RequiredVersion` instead.
See also the `Install-Module` documentation: https://learn.microsoft.com/en-us/powershell/module/powershellget/install-module?view=powershellget-3.x

**Comment by pim-simons** [comment]
Fixed this in the release notes of the releases going back to version `1.0.0`

**Comment by pim-simons** [comment]
> @pim-simons , it will also have to be fixed in the release pipeline here: [`main`/build/psgallery-release.yml](https://github.com/arcus-azure/arcus.scripting/blob/main/build/psgallery-release.yml) where we draft the release notes structure.

You are right (as always 😉), see https://github.com/arcus-azure/arcus.scripting/pull/443 for the PR

**Comment by stijnmoreels** [comment]
> > @pim-simons , it will also have to be fixed in the release pipeline here: [`main`/build/psgallery-release.yml](https://github.com/arcus-azure/arcus.scripting/blob/main/build/psgallery-release.yml) where we draft the release notes structure.
> 
> You are right (as always 😉), see #443 for the PR

![MissPiggyTheMuppetsGIF](https://github.com/user-attachments/assets/543c7546-890e-48a0-994a-a525addeb09b)
