### ISSUE TITLE
Every module should bring their dependencies with them

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.scripting#55]
**Is your feature request related to a problem? Please describe.**
Every module should bring their dependencies with them so that we don't have to care about dependencies of Arcus

For example for Key Vault, it assumes that it's pre-installed rather than define it as a dependency: https://github.com/arcus-azure/arcus.scripting/blob/master/src/Arcus.Scripting.KeyVault/Arcus.Scripting.KeyVault.psd1#L51

**Comment by tomkerkhove** [comment]
Example: https://github.com/Azure/azure-powershell/blob/master/src/EventHub/EventHub/Az.EventHub.psd1#L56

**Comment by mbraekman** [comment]
Aha, it does work with Az-modules now - some time ago this wasn't supported - but yep, should be noted as requiredModules.

**Comment by stijnmoreels** [comment]
Can we already do this in v0.1, @mbraekman ? Maybe better?

**Comment by tomkerkhove** [comment]
I think it's best to add this for v0.1 to be honest since we depend on those.

**Comment by mbraekman** [comment]
I believe this has been sorted for the following modules via #69 :
- ApiManagement
- DataFactory
- KeyVault
- Storage

@stijnmoreels can you confirm, if this is the case - I'll move this back to milestone v0.2.0 in order to keep track of this for the next modules to create.

**Comment by stijnmoreels** [comment]
Yes, that's correct, all those projects have their dependencies with them. Although, only the ApiManagement project has (now) a specific version of a required module. Should this be the case for every project?

**Comment by mbraekman** [comment]
> Should this be the case for every project?
Yes, please.

**Comment by mbraekman** [comment]
Closing this as it has been implemented for v0.1.0-modules.
For futher modules, should be part of the actual workload/issue when creating the module.
