### ISSUE TITLE
Provide script to disable an Azure Logic App

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.scripting#6]
Provide script to disable an Azure Logic App

**Comment by mbraekman** [comment]
Based on the following script:
https://codit.visualstudio.com/Invictus%20Templates/_git/invictus-templates?path=%2Fdeploy%2FAzure-DisableLogicApps.ps1

This script does require the presence of a "deploy-orderControl.json"-file which acts as configuration to indicate which Logic Apps are to be disabled, in what order.
Documentation on this can be found here:
https://codit.visualstudio.com/Invictus%20Templates/_wiki/wikis/Invictus%20Templates/115/EnableDisable-Logic-Apps

**Comment by mbraekman** [comment]
@stijnmoreels, I think we can set this to "done" and close the issue?

**Comment by mbraekman** [comment]
Scratch that, I was confusing this with #20, which is already closed.

**Comment by mbraekman** [comment]
Moved to v0.2.1 as this can be easily implemented when fixing the bug logged in #105
