### ISSUE TITLE
Provide the correct API key to publish to the PowerShell Gallery

### ISSUE THREAD

**Issue by stijnmoreels** [arcus-azure/arcus.scripting#64]
**Is your feature request related to a problem? Please describe.**
As of today @stijnmoreels 's account is used to test the publishing to the PowerShell Gallery.

**Describe the solution you'd like**
We should update the service connection to use the API key of the right account before publishing.

**Comment by tomkerkhove** [comment]
This is now configured and allows you to push packages with glob `Arcus.Scripting.*`
