### ISSUE TITLE
Provide package metadata

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.scripting#65]
**Is your feature request related to a problem? Please describe.**
Provide package metadata to improve the consumer experience and make it easier to use.

**Describe the solution you'd like**
Add the following information to every `psd1`:
- Include `PowerShellVersion` (see [sample](https://github.com/Azure/azure-powershell/blob/master/src/ApiManagement/ApiManagement/Az.ApiManagement.psd1#L38))
- Add `Tags`, `LicenseUri`, `ProjectUri`, `IconUri` in private data (see [sample](https://github.com/Azure/azure-powershell/blob/master/src/ApiManagement/ApiManagement/Az.ApiManagement.psd1#L186))

**Comment by tomkerkhove** [comment]
What do you think @mbraekman ?

**Comment by mbraekman** [comment]
Yes, this should be added, preferably in v0.1.0
