### ISSUE TITLE
Provide script to enable an Azure Logic Apps based on configuration-file

### ISSUE THREAD

**Issue by tomkerkhove** [arcus-azure/arcus.scripting#7]
Provide script to enable an Azure Logic App

**Comment by mbraekman** [comment]
Based on the following script:
https://codit.visualstudio.com/Invictus%20Templates/_git/invictus-templates?path=%2Fdeploy%2FAzure-EnableLogicApps.ps1

This script does require the presence of a "deploy-orderControl.json"-file which acts as configuration to indicate which Logic Apps are to be enabled, in what order.
Documentation on this can be found here:
https://codit.visualstudio.com/Invictus%20Templates/_wiki/wikis/Invictus%20Templates/115/EnableDisable-Logic-Apps

**Comment by mbraekman** [comment]
Would this be something which can be set up quite easily, since it is similar to #20 ?
Looking into what we can/should include into the next release, to make the scripts that have already been created available.
