### ISSUE TITLE
Provide script to import certificate as base64-string into Azure Key Vault 

### ISSUE THREAD

**Issue by mbraekman** [arcus-azure/arcus.scripting#71]
**Is your feature request related to a problem? Please describe.**
Provide a script to help with uploading a certificate as a secret into Azure Key Vault.

**Describe the solution you'd like**
Read the provided certificate as byte-array to convert to base64 before uploading with multi-line support to Azure Key Vault.

Example of such a script can be found here:
https://github.com/mbraekman/Powershell/blob/master/Azure/Create%20KeyVault%20Secret%20-%20Certificate%20as%20Base64.ps1

**Comment by stijnmoreels** [comment]
Maybe we can provide an extra argument to the already exiting #17 script for the encoding of the to-be-imported file instead of two seperate commands? @mbraekman

**Comment by mbraekman** [comment]
While I'm not opposed to that suggestion, I think we should create a seperate one, to keep in line with the user-friendliness setup where we split up enable/disable or start/stop scripts as well.
