### ISSUE TITLE
Rename Arcus.Scripting.Storage to Arcus.Scripting.Storage.Table

### ISSUE THREAD

**Issue by mbraekman** [arcus-azure/arcus.scripting#72]
**Is your feature request related to a problem? Please describe.**
Create a specific module for table-storage operations.
As was discussed in #54 

**Describe the solution you'd like**
The current module Arcus.Scripting.Storage only contains operations related to Table Storage.
Rename this module to reflect this, and in the future a new overlapping module Arcus.Scripting.Storage will be created, as mentioned in #67

**Comment by stijnmoreels** [comment]
Hmm, not entirely sure how this should be set  up. I'll make a PR with what I have now and you can comment on what I did wrong 😅 .

**Comment by tomkerkhove** [comment]
Basically just rename the moduble that we already have from `Arcus.Scripting.Storage` to `Arcus.Scripting.Storage.Table` and you should be good to go.
