### ISSUE TITLE
Announcement Arcus.Scripting v0.1.0

### ISSUE THREAD

**Issue by mbraekman** [arcus-azure/arcus.scripting#74]
**Is your feature request related to a problem? Please describe.**
Let the people know what we've been doing!

**Describe the solution you'd like**
Write an announcement about the initial version of Arcus.Scripting become available to the world.

**Describe alternatives you've considered**
Should this be in the forms of a blog-post? 
Or can we stick to an announcement on Yammer/Teams? 
@tomkerkhove

**Comment by tomkerkhove** [comment]
A blog post would be perfect as we go beyond Codit!

An internal announcement with a link to the blog post is a good way for internal buzz, certainly to guide new folks based from what we had internally.

**Comment by stijnmoreels** [comment]
I'll propose something in [arcus](https://github.com/arcus-azure/arcus).

**Comment by stijnmoreels** [comment]
I hope with the testing on the PowerShell gallery, I didn't f*cked up the release numbers; making it unavailable to release v0.1 but something greater (or lesser) 😓 .

**Comment by stijnmoreels** [comment]
Already created WordPress blog post of it. Waiting for the actually release.

**Comment by tomkerkhove** [comment]
Thanks!

**Comment by stijnmoreels** [comment]
Released and have let it known that the WordPress blog post is ready for publishing. Waiting with closing this issue when the post is acutally published.
