### ISSUE TITLE
Add table of contents to documentation

### ISSUE THREAD

**Issue by mbraekman** [arcus-azure/arcus.scripting#78]
**Is your feature request related to a problem? Please describe.**
Add table of contents to documentation

**Describe the solution you'd like**
In order to quickly provide an overview to anyone looking at the documentation, provide a table of contents, which:
- links to the actual section
- provides a quick overview of capabilities

Once this is done, we can publish the documentation as final (no preview) so it becomes available once the modules are published onto the PowerShell Gallery.

**Additional context**
As an example:
![image](https://user-images.githubusercontent.com/16165565/88809645-a8879e00-d1b4-11ea-9751-951514d5d41b.png)

**Comment by stijnmoreels** [comment]
You mean you want a table of contents at the index page that lists _all_ commands?
Now we have at the index page a reference to each separate file that relates to a topic (storage, key vault...).

![image](https://user-images.githubusercontent.com/9039753/88885876-9b60c280-d239-11ea-8cdb-25a7ad1b2b57.png)

Isn't that enough?

**Comment by mbraekman** [comment]
What I mean is that we should have an overview of the available commands, per page.
For instance, if I browse to the Azure Key Vault-module specific page, I want to be able to quickly see what the capabilities are, instead of having to scroll through the entire page. 
While currently we only have 1 or 2 operations per topic, in the future this will increase, and not having such an overview would cause people you just skip the module entirely - or at least, that's what I often think when I just see a very long page without table of contents.

**Comment by tomkerkhove** [comment]
I have to agree on that!

What Maxim means is that at the top of every page it should list all the modules with links to their respective docs:
![image](https://user-images.githubusercontent.com/4345663/88890094-65bfd780-d241-11ea-8b05-8c7d1baf776f.png)

This would improve discoverability instead of having to scroll through all the commands and see what it supports.

Can be as simple as this for example: (but up to Maxim)
```markdown
- [**Enable the trigger of a Azure Data Factory pipeline**](foo)
- [**Disable the trigger of a Azure Data Factory pipeline**](bar)
```

**Comment by mbraekman** [comment]
Exactly this ^^
With the exception of foo and bar ;)
