### ISSUE TITLE
A script to update SQL database content

### ISSUE THREAD

**Issue by gverstraete** [arcus-azure/arcus.scripting#93]
Would it be a good idea to add here the scripts we use for upgrading our SQL database structures?

I know it's used by several teams by several members? 
Let me know what you think. If you are ok with it I create a first PR on this.

**Comment by tomkerkhove** [comment]
Thanks for the suggestion!

What are those scripts doing exactly? Can you share some more details on that?

**Comment by gverstraete** [comment]
The script is creating a database version table. It has a version number and a description. Aftwards you can do incremental updates to your database via a sql file which is ordered by the version number. Once tested in the first environment, you can make it part of your release pipeline and your database get's automatically updated.

**Comment by mbraekman** [comment]
Sounds interesting!
Something which is to be created underneath an Arcus.Scripting.Sql-folder in the sources.
We'll have to take a look at how to update the documentation though, as it's currently purely PS-minded, but nothing blocking that would be blocking this.

**Comment by tomkerkhove** [comment]
Well in theory it would be PowerShell executing those SQL statements if I'm not mistaken, something tells me this comes from a project I did 4 years ago and it's still being passed around 😂 I hope I'm wrong haha

**Comment by gverstraete** [comment]
It is a powershell scipt - actually two - I can just create PR and then we can decide? - And it could be very well that script Tom!

**Comment by tomkerkhove** [comment]
Sure, would be happy to review that PR!

**Comment by mbraekman** [comment]
Owkay, my bad, PS is good 😄
