### ISSUE TITLE
Allign parameter-names

### ISSUE THREAD

**Issue by mbraekman** [arcus-azure/arcus.scripting#95]
**Describe the bug**
APIM/Storage.Table use "ResourceGroup"
Other modules use "ResourceGroupName"
There should be consistent use of the parameter-name "ResourceGroupName".

**Comment by stijnmoreels** [comment]
Hmm, that means breaking changes. Sure that this is for v0.2? Not v1?

**Comment by mbraekman** [comment]
Well, perhaps that would've been more of a v0.1.1.
But since not a lot of people use it (based on the feedback Tom was able to collect), might as well include this in v0.2 and have it released together with the new scripts that have been created.

**Comment by stijnmoreels** [comment]
Still think that we should include this breaking change in the next minor release? Or should we move to the next major?
